spring:
  application:
    name: fleetlab-backend
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

